print("Hi!")
print(10)
print("Hi" + str(5))
print("Hi!\n")
print("I am 5 years old!")
print("Hello " + "world!")
print("Hello","world!")
print("Hello","world!", sep=" 😊 ")
print("Hello","world!", sep="\n")
print("Hello","world!", end=" ")
print("YAY!")