#Raj was with his 5 friends
print("He was with his five friends,")
print("Armaan, Reva, Ben, Ella, and Ria.")
Armaan = input("Set Armaan's birthday (Format: 00/00/00): ")
Reva = input("Set Reva's birthday (Format: 00/00/00): ")
Ben = input("Set Ben's birthday (Format: 00/00/00): ")
Ella = input("Set Ella's birthday (Format: 00/00/00): ")
Ria = input("Set Ria's birthday (Format: 00/00/00): ")
print("During the picnic, Raj asked his friends for their birthdays! They replied:")
print("Armaan: My birthday is " + Armaan)
print("Reva: Cool! Mine is " + Reva)
print("Ben: Mine is "+ Ben)
print("Ella: My birthday is near! It is " + Ella)
print("Ria: Mine is " + Ria)